/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package warpay.ui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import warpay.data.AccountData;
import warpay.util.Conn;
import warpay.util.Extension;

/**
 *
 * @author irkham
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public LoginUI() {
        setUndecorated(true);
        initComponents();
        initPlaceholder();
        initConnection();

        fieldUser.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
            }
        });

        fieldPass.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }

                if (fieldPass.getPassword().length >= 19) {
                    e.consume();
                }
            }
        });

    }

    Connection conn = null;

    private void initPlaceholder() {
        Extension.addPlaceholderStyle(fieldUser);
        Extension.addPlaceholderStyle(fieldPass);
    }

    private void initConnection() {
        conn = Conn.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        roundPanel = new warpay.swing.RoundPanel();
        head = new warpay.swing.RoundPanel();
        tagLine = new javax.swing.JLabel();
        main = new warpay.swing.RoundPanel();
        labelWar = new javax.swing.JLabel();
        labelPay = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        fieldUser = new warpay.swing.field.TextField();
        labelPass = new javax.swing.JLabel();
        fieldPass = new warpay.swing.field.PasswordField();
        buttonCancel = new warpay.swing.button.Button();
        buttonLogin = new warpay.swing.button.Button();
        foot = new warpay.swing.RoundPanel();
        labelFoot = new javax.swing.JLabel();
        buttonSignup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        setIconImage(Extension.getFrameIcon(getClass().getResource("/assets/image/warpay.png")));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(352, 492));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        contentPane.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        contentPane.setPreferredSize(getPreferredSize());
        contentPane.setLayout(null);

        roundPanel.setBackground(new java.awt.Color(254, 254, 254));

        head.setBackground(new java.awt.Color(81, 203, 255));

        tagLine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tagLine.setForeground(new java.awt.Color(255, 255, 255));
        tagLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tagLine.setText("SECURE AND FAST DIGITAL WALLET SYSTEM");
        tagLine.setPreferredSize(new java.awt.Dimension(294, 20));

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tagLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tagLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        main.setBackground(new java.awt.Color(81, 203, 255));
        main.setPreferredSize(new java.awt.Dimension(328, 356));

        labelWar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelWar.setForeground(new java.awt.Color(255, 255, 255));
        labelWar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWar.setText("WAR");
        labelWar.setPreferredSize(new java.awt.Dimension(114, 64));

        labelPay.setFont(labelWar.getFont());
        labelPay.setForeground(labelWar.getForeground());
        labelPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPay.setText("PAY");
        labelPay.setPreferredSize(labelWar.getPreferredSize());

        labelUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        labelUser.setLabelFor(fieldUser);
        labelUser.setText("User ID");

        fieldUser.setText(warpay.ui.Text.UID);
        fieldUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldUser.setPreferredSize(new java.awt.Dimension(200, 41));
        fieldUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldUserFocusLost(evt);
            }
        });

        labelPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPass.setForeground(new java.awt.Color(255, 255, 255));
        labelPass.setLabelFor(fieldPass);
        labelPass.setText("Passcode");

        fieldPass.setText(warpay.ui.Text.PASS);
        fieldPass.setEchoChar('\u0000');
        fieldPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fieldPass.setPreferredSize(new java.awt.Dimension(200, 41));
        fieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPassFocusLost(evt);
            }
        });
        fieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldPassKeyReleased(evt);
            }
        });

        buttonCancel.setBackground(new java.awt.Color(0, 150, 255));
        buttonCancel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCancel.setText(Text.CANCEL);
        buttonCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonCancel.setPreferredSize(new java.awt.Dimension(91, 40));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonLogin.setBackground(new java.awt.Color(0, 150, 255));
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText(Text.LOGIN);
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonLogin.setPreferredSize(new java.awt.Dimension(91, 40));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelWar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPass)
                            .addComponent(labelUser)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainLayout.createSequentialGroup()
                                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(64, 64, 64))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelWar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUser)
                .addGap(0, 0, 0)
                .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelPass)
                .addGap(0, 0, 0)
                .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        foot.setBackground(new java.awt.Color(81, 203, 255));

        labelFoot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFoot.setForeground(new java.awt.Color(255, 255, 255));
        labelFoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoot.setLabelFor(buttonSignup);
        labelFoot.setText("Don't have an account?");

        buttonSignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonSignup.setText(Text.SIGNUP);
        buttonSignup.setPreferredSize(new java.awt.Dimension(50, 20));
        buttonSignup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                buttonSignupMouseMoved(evt);
            }
        });
        buttonSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSignupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout footLayout = new javax.swing.GroupLayout(foot);
        foot.setLayout(footLayout);
        footLayout.setHorizontalGroup(
            footLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(labelFoot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        footLayout.setVerticalGroup(
            footLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(footLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelFoot)
                    .addComponent(buttonSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout roundPanelLayout = new javax.swing.GroupLayout(roundPanel);
        roundPanel.setLayout(roundPanelLayout);
        roundPanelLayout.setHorizontalGroup(
            roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        roundPanelLayout.setVerticalGroup(
            roundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(foot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        contentPane.add(roundPanel);
        roundPanel.setBounds(0, 0, 353, 492);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(352, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        this.requestFocusInWindow();
    }//GEN-LAST:event_formFocusGained

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        userLogin();
    }//GEN-LAST:event_buttonLoginActionPerformed

    private boolean isInputValid(String uid, String pass) {
        if (uid.isEmpty() || uid.equalsIgnoreCase(Text.UID)) {
            JOptionPane.showMessageDialog(null, "Please enter your account id.");
            fieldUser.requestFocusInWindow();
            return false;
        }

        if (pass.isEmpty() || pass.equalsIgnoreCase(Text.PASS)) {
            JOptionPane.showMessageDialog(null, "Please enter your passcode.");
            fieldPass.requestFocusInWindow();
            return false;
        }

        return true;
    }

    private void userLogin() {
        String user = fieldUser.getText();
        String pass = String.valueOf(fieldPass.getPassword());

        if (isInputValid(user, pass)) {

            try {
                int id, cust_id;
                double balance;
                String fname, lname, fullname, email, encpass;
                int uid = Integer.valueOf(user);

                PreparedStatement pst = conn.prepareStatement("SELECT * FROM account_customers WHERE account_id = ? AND passcode=MD5(?)");

                pst.setInt(1, uid);
                pst.setString(2, pass);

                try (ResultSet acc_cust = pst.executeQuery()) {
                    if (acc_cust.next()) {
                        id = acc_cust.getInt(1);
                        cust_id = acc_cust.getInt(2);
                        encpass = acc_cust.getString(3);

                        pst = conn.prepareStatement("SELECT * FROM accounts WHERE account_id = ?");

                        pst.setInt(1, id);

                        try (ResultSet acc = pst.executeQuery()) {
                            if (acc.next()) {
                                balance = acc.getInt(2);

                                pst = conn.prepareStatement("SELECT * FROM customers WHERE customer_id = ?");

                                pst.setInt(1, cust_id);

                                try (ResultSet cust = pst.executeQuery()) {
                                    if (cust.next()) {
                                        fname = cust.getString(2);
                                        lname = cust.getString(3);
                                        fullname = fname + " " + lname;
                                        email = cust.getString(4);

                                        AccountData.getInstance().setAccountId(id);
                                        AccountData.getInstance().setBalance(balance);
                                        AccountData.getInstance().setCustomerId(cust_id);
                                        AccountData.getInstance().setEmail(email);
                                        AccountData.getInstance().setFirstname(fname);
                                        AccountData.getInstance().setFullname(fullname);
                                        AccountData.getInstance().setLastname(lname);
                                        AccountData.getInstance().setPasscode(encpass);

                                        dispose();
                                        java.awt.EventQueue.invokeLater(() -> {
                                            new MainUI().setVisible(true);
                                        });
                                    }
                                }
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Wrong id or password, please double check it");
                    }
                }
            } catch (SQLException | HeadlessException e) {
                System.err.println(e.getMessage());
                JOptionPane.showMessageDialog(null,
                        e.getMessage(), "Error",
                        JOptionPane.INFORMATION_MESSAGE
                );
                System.exit(0);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Id and passcode must be a set of num");
            }
        }
    }


    private void fieldUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUserFocusGained
        if (fieldUser.getText().equalsIgnoreCase(Text.UID)) {
            fieldUser.setText("");
            fieldUser.requestFocus();
            Extension.removePlaceholderStyle(fieldUser);
        }
    }//GEN-LAST:event_fieldUserFocusGained

    private void fieldUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUserFocusLost
        if (fieldUser.getText().length() == 0) {
            Extension.addPlaceholderStyle(fieldUser);
            fieldUser.setText(Text.UID);
        }
    }//GEN-LAST:event_fieldUserFocusLost

    private void fieldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPassFocusGained
        String pass = String.valueOf(fieldPass.getPassword()).trim();
        if (pass.equalsIgnoreCase(Text.PASS)) {
            fieldPass.setText("");
            fieldPass.requestFocus();
            fieldPass.setEchoChar('\u2022');
            Extension.removePlaceholderStyle(fieldPass);
        }
    }//GEN-LAST:event_fieldPassFocusGained

    private void fieldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPassFocusLost
        if (fieldPass.getPassword().length == 0) {
            Extension.addPlaceholderStyle(fieldPass);
            fieldPass.setText(Text.PASS);
            fieldPass.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_fieldPassFocusLost

    private void fieldPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPassKeyReleased
        String pass = String.valueOf(fieldPass.getPassword()).trim();
        if (pass.isEmpty() || pass.equalsIgnoreCase(Text.PASS)) {
            fieldPass.setShowAndHide(false);
        } else {
            fieldPass.setShowAndHide(true);
        }
    }//GEN-LAST:event_fieldPassKeyReleased

    private void buttonSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignupMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            dispose();
            new SignUpUI().setVisible(true);
        });
    }//GEN-LAST:event_buttonSignupMouseClicked

    private void buttonSignupMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignupMouseMoved
        buttonSignup.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_buttonSignupMouseMoved
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private warpay.swing.button.Button buttonCancel;
    private warpay.swing.button.Button buttonLogin;
    private javax.swing.JLabel buttonSignup;
    private javax.swing.JPanel contentPane;
    private warpay.swing.field.PasswordField fieldPass;
    private warpay.swing.field.TextField fieldUser;
    private warpay.swing.RoundPanel foot;
    private warpay.swing.RoundPanel head;
    private javax.swing.JLabel labelFoot;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPay;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelWar;
    private warpay.swing.RoundPanel main;
    private warpay.swing.RoundPanel roundPanel;
    private javax.swing.JLabel tagLine;
    // End of variables declaration//GEN-END:variables
}
