/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warpay.ui;

import java.awt.CardLayout;
import warpay.data.AccountData;

/**
 *
 * @author irkham
 */
public class ProfileUI extends javax.swing.JPanel {

    /**
     * Creates new form ProfileUI
     */
    public ProfileUI() {
        menu = new ProfileMenuUI();
        settings = new ProfileSettingsUI();
        security = new SecuritySettingsUI();
        
        initComponents();
        
        cards.add(menu, MENUPANEL);
        cards.add(settings, SETTINGSPANEL);
        cards.add(security, SECURITYPANEL);
        
        setProfile();

        showCard("MENU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new warpay.swing.RoundPanel();
        avatarUser = new warpay.swing.ImageAvatar();
        labelUname = new javax.swing.JLabel();
        labelUid = new javax.swing.JLabel();
        cards = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(650, 580));

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setPreferredSize(getPreferredSize());

        avatarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/person.png"))); // NOI18N
        avatarUser.setPreferredSize(new java.awt.Dimension(56, 56));

        labelUname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUname.setForeground(new java.awt.Color(255, 255, 255));
        labelUname.setText("FULL NAME");
        labelUname.setPreferredSize(new java.awt.Dimension(558, 24));

        labelUid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUid.setForeground(new java.awt.Color(255, 255, 255));
        labelUid.setText("ACCOUNT ID");
        labelUid.setPreferredSize(new java.awt.Dimension(558, 22));

        cards.setOpaque(false);
        cards.setPreferredSize(new java.awt.Dimension(650, 500));
        cards.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(avatarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelUid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelUname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(labelUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(labelUid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(avatarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private warpay.swing.ImageAvatar avatarUser;
    private warpay.swing.RoundPanel bg;
    private static javax.swing.JPanel cards;
    static javax.swing.JLabel labelUid;
    static javax.swing.JLabel labelUname;
    // End of variables declaration//GEN-END:variables

    ProfileMenuUI menu;
    ProfileSettingsUI settings;
    SecuritySettingsUI security;
    static final String MENUPANEL = "Profile Menu";
    static final String SETTINGSPANEL = "Profile Settings UI";
    static final String SECURITYPANEL = "Security Settings UI";

    static void setProfile() {
        String fname = AccountData.getInstance().getFirstname();
        String lname = AccountData.getInstance().getLastname();
        String uid = String.valueOf(AccountData.getInstance().getAccountId());
        String fullName;

        if (fname.isEmpty() && lname.isEmpty()) {
            fullName = "User";
        } else if (!fname.isEmpty() && lname.isEmpty()) {
            fullName = fname;
        } else if (fname.isEmpty() && !lname.isEmpty()) {
            fullName = lname;
        } else {
            fullName = AccountData.getInstance().getFullname();
        }

        labelUname.setText(fullName);
        labelUid.setText(uid);
    }

    static void showCard(String name) {
        CardLayout cl = (CardLayout) (cards.getLayout());
        cl.show(cards, name);
    }
}
