/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warpay.ui;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author irkham
 */
public class ProfileMenuUI extends javax.swing.JPanel {

    /**
     * Creates new form ProfileMenuUI
     */
    public ProfileMenuUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new warpay.swing.RoundPanel();
        panelProfileSet = new warpay.swing.RoundPanel();
        labelProfileSet = new javax.swing.JLabel();
        iconProfileSet = new javax.swing.JLabel();
        buttonProfileSet = new javax.swing.JButton();
        panelSecuritySet = new warpay.swing.RoundPanel();
        labelSecuritySet = new javax.swing.JLabel();
        iconSecuritySet = new javax.swing.JLabel();
        buttonSecuritySet = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(650, 500));

        body.setBackground(new java.awt.Color(81, 203, 255));
        body.setPreferredSize(new java.awt.Dimension(650, 500));

        panelProfileSet.setBackground(new java.awt.Color(255, 255, 255));
        panelProfileSet.setMinimumSize(new java.awt.Dimension(70, 70));

        labelProfileSet.setBackground(new java.awt.Color(0, 0, 0));
        labelProfileSet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelProfileSet.setText("PROFILE SETTINGS");
        labelProfileSet.setPreferredSize(new java.awt.Dimension(161, 24));

        iconProfileSet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iconProfileSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/profile_setting.png"))); // NOI18N

        buttonProfileSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/navigate_next_48.png"))); // NOI18N
        buttonProfileSet.setBorderPainted(false);
        buttonProfileSet.setContentAreaFilled(false);
        buttonProfileSet.setPreferredSize(new java.awt.Dimension(48, 48));
        buttonProfileSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfileSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProfileSetLayout = new javax.swing.GroupLayout(panelProfileSet);
        panelProfileSet.setLayout(panelProfileSetLayout);
        panelProfileSetLayout.setHorizontalGroup(
            panelProfileSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileSetLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconProfileSet)
                .addGap(12, 12, 12)
                .addComponent(labelProfileSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonProfileSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        panelProfileSetLayout.setVerticalGroup(
            panelProfileSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileSetLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelProfileSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconProfileSet)
                    .addComponent(labelProfileSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProfileSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        panelSecuritySet.setBackground(new java.awt.Color(255, 255, 255));
        panelSecuritySet.setMinimumSize(new java.awt.Dimension(70, 70));

        labelSecuritySet.setBackground(new java.awt.Color(0, 0, 0));
        labelSecuritySet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSecuritySet.setText("SECURITY SETTINGS");
        labelSecuritySet.setPreferredSize(new java.awt.Dimension(174, 24));

        iconSecuritySet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iconSecuritySet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/security_setting.png"))); // NOI18N

        buttonSecuritySet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image/navigate_next_48.png"))); // NOI18N
        buttonSecuritySet.setBorderPainted(false);
        buttonSecuritySet.setContentAreaFilled(false);
        buttonSecuritySet.setPreferredSize(new java.awt.Dimension(48, 48));
        buttonSecuritySet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSecuritySetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSecuritySetLayout = new javax.swing.GroupLayout(panelSecuritySet);
        panelSecuritySet.setLayout(panelSecuritySetLayout);
        panelSecuritySetLayout.setHorizontalGroup(
            panelSecuritySetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecuritySetLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconSecuritySet)
                .addGap(12, 12, 12)
                .addComponent(labelSecuritySet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(buttonSecuritySet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        panelSecuritySetLayout.setVerticalGroup(
            panelSecuritySetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecuritySetLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelSecuritySetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelSecuritySet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconSecuritySet)
                    .addComponent(buttonSecuritySet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProfileSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSecuritySet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panelProfileSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelSecuritySet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSecuritySetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSecuritySetActionPerformed
        ProfileUI.showCard(ProfileUI.SECURITYPANEL);
    }//GEN-LAST:event_buttonSecuritySetActionPerformed

    private void buttonProfileSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfileSetActionPerformed
        ProfileUI.showCard(ProfileUI.SETTINGSPANEL);
    }//GEN-LAST:event_buttonProfileSetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private warpay.swing.RoundPanel body;
    private javax.swing.JButton buttonProfileSet;
    private javax.swing.JButton buttonSecuritySet;
    private javax.swing.JLabel iconProfileSet;
    private javax.swing.JLabel iconSecuritySet;
    private javax.swing.JLabel labelProfileSet;
    private javax.swing.JLabel labelSecuritySet;
    private warpay.swing.RoundPanel panelProfileSet;
    private warpay.swing.RoundPanel panelSecuritySet;
    // End of variables declaration//GEN-END:variables
}
